### ISSUE TITLE
Optional initialisation of Sentry - and avoid exposing the DSN?

### ISSUE THREAD

**Issue by alanbchristie** [xchem/fragalysis-backend#216]
Sentry's cool but its initialisation in the backend is not optional. Consequently if you run a migration on your desktop and it fails then you get an alarm in your chosen Sentry recipient (slack in this case).

1. Do you really want every build problem from everyone around the world whose forked the repo written to Slack?
2. Do you want to give the world your DSN key? i.e. anyone anywhere can send alerts to your Sentry account.

Suggest: -

-   Pull Sentry DSN from an environment variable (e.g. `FRAGALYSIS_BACKEND_SENTRY_DNS`) rather than have it hard-coded
-   Add logic that prevents the intitialisation of Sentry if the variable is -blank- or not defined
-   Default value provided by encrypted variable in the Kubernetes Ansible code (separate repo) so "official" stacks report errors

An added advantage:

Different stack deployments can use different DSN keys - so you know the alert belongs to deployment/customer X, Y or Z.

**Comment by alanbchristie** [comment]
This is what I basically do in Python when initialising the sentry SDK...

```python
# Initialise sentry SDK?
SENTRY_DSN = os.environ.get('SENTRY_DSN')
if SENTRY_DSN:
    _LOGGER.info('Initialising sentry...')
    sentry_sdk.init(SENTRY_DSN)
    _LOGGER.info('Initialised.')
```

> We'll need to co-ordinate this change with the templates in the dls-fragalysis-stack-kubernetes repo. We can then expose the DSN as an Ansible variable and users will then be able to pass in their own values (or leave it blank).

> We'll also need to co-ordinate each customer regarding a new fragalysis release - remembering that some use an S3 loader for data population

**Comment by alanbchristie** [comment]
Version **2020.58** of the dls-fragalysis-stack-kubernetes repo now exposes the Ansible variable `stack_backend_sentry_dsn` (with a default of ''). If set the environment variable `FRAGALYSIS_BACKEND_SENTRY_DNS` is set in the fragalysis container to its value.

**Comment by duncanpeacock** [comment]
Patch : https://github.com/duncanpeacock/fragalysis-backend/tree/issue-216-sentry-dns
raised for the fragalysis backend to check FRAGALYSIS_BACKEND_SENTRY_DNS is present and use it as an environment variable for Sentry DNS as suggested. If variable is not present then Sentry is not actived.
