### ISSUE TITLE
All job execution commands should fail immediately if Squonk is not configured

### ISSUE THREAD

**Issue by tdudgeon** [xchem/fragalysis-backend#333]
We've hit problems with debugging job execution problems when the route cause was that the `SQUONK_*` environment variables were not set. Seems that files uploads are tried, but of course fail.

Would be better if all executions related to job execution fail immediately with an appropriate error message if those env variables are not defined.

**Comment by alanbchristie** [comment]
I’ve looked at this and there’s a `react(request)` method documented as **THIS IS THE FIRST API THAT THE FRONT END CALLS**. It should be returning a `context` that has the property/key `squonk_available` which will be `false` unless both variables are set.

So, if neither variable is set this should be reflected in context where `squonk_available` is `false` - e.g. the UI should not make squonk calls unless this us true.

**Comment by boriskovar-m2ms** [comment]
Just checked and DJANGO_CONTEXT there is indeed field squonk_available but it's not mentioned anywhere in the designs and never heard of it before but this is exactly what I need. Going to add it to the code right now.

**Comment by alanbchristie** [comment]
Ok - apologies - it was pre-exiting code so I assumed you knew about it.
